#ifndef _ERR_HPP_
#define _ERR_HPP_

enum ErrorCode {
  OK,
  FAIL_TO_ALLOCATE_MEMORY = 5,
  FAIL_TO_OPEN_FILE,
  FAIL_TO_RESOLVE_PATH,
  TOO_FEW_ARGUMENTS,
  TOO_MANY_ARGUMENTS,
  ZIP_WRITTER_FAIL
};

#endif  //_ERR_HPP_